package com.capg.smartcourier.entity;

import jakarta.persistence.*;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Address Entity
 *
 * Represents pickup and delivery addresses in the Smart Courier System.
 */
@Entity
public class Address {

    /**
     * Unique identifier for the address
     * Auto-generated by the database using IDENTITY strategy
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Type of address indicating its role in the delivery
     * Values: "SENDER" (pickup location) or "RECEIVER" (delivery location)
     * Determines how the address is used in the delivery workflow
     */
    private String type; // SENDER / RECEIVER

    /**
     * Full name of the contact person at this address
     * Used for delivery coordination and verification
     * Required for both sender and receiver addresses
     */
    private String name;

    /**
     * Phone number for contact at this address
     * Used for delivery notifications and coordination
     * Must be valid phone number format
     */
    private String phone;

    /**
     * Complete street address including building number and street name
     * Primary address information for delivery location
     * Must be detailed enough for reliable delivery
     */
    private String address;

    /**
     * City where the address is located
     * Used for regional routing, pricing, and delivery planning
     * Important for calculating delivery zones and timeframes
     */
    private String city;

    /**
     * Associated delivery information
     * Many-to-One relationship: multiple addresses can belong to one delivery
     * Foreign key relationship with delivery_id column
     * JsonIgnore prevents circular serialization in REST responses
     */
    @ManyToOne
    @JoinColumn(name = "delivery_id")
    @JsonIgnore
    private Delivery delivery;

    /**
     * Default constructor required by JPA
     */
    public Address() {}

    // Getters & Setters

    /**
     * Get the address ID
     * @return the unique identifier of this address
     */
    public Long getId() { return id; }

    /**
     * Set the address ID
     * @param id the unique identifier to set
     */
    public void setId(Long id) { this.id = id; }

    /**
     * Get the address type
     * @return "SENDER" or "RECEIVER" indicating the address role
     */
    public String getType() { return type; }

    /**
     * Set the address type
     * @param type "SENDER" for pickup or "RECEIVER" for delivery
     */
    public void setType(String type) { this.type = type; }

    /**
     * Get the contact name
     * @return the full name of the contact person
     */
    public String getName() { return name; }

    /**
     * Set the contact name
     * @param name the full name of the contact person
     */
    public void setName(String name) { this.name = name; }

    /**
     * Get the contact phone number
     * @return the phone number for delivery coordination
     */
    public String getPhone() { return phone; }

    /**
     * Set the contact phone number
     * @param phone the phone number for delivery coordination
     */
    public void setPhone(String phone) { this.phone = phone; }

    /**
     * Get the street address
     * @return the complete street address for delivery
     */
    public String getAddress() { return address; }

    /**
     * Set the street address
     * @param address the complete street address for delivery
     */
    public void setAddress(String address) { this.address = address; }

    /**
     * Get the city
     * @return the city where the address is located
     */
    public String getCity() { return city; }

    /**
     * Set the city
     * @param city the city where the address is located
     */
    public void setCity(String city) { this.city = city; }

    /**
     * Get the associated delivery
     * @return the delivery that this address belongs to
     */
    public Delivery getDelivery() { return delivery; }

    /**
     * Set the associated delivery
     * @param delivery the delivery to associate with this address
     */
    public void setDelivery(Delivery delivery) { this.delivery = delivery; }
}