package com.capg.smartcourier.entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.*;
import java.util.List;

/**
 * Delivery Entity
 *
 * Represents a delivery order in the Smart Courier System.
 */
@Entity
public class Delivery {

    /**
     * Unique identifier for the delivery
     * Auto-generated by the database using IDENTITY strategy
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Unique tracking number for the delivery
     * Format: 10-20 uppercase alphanumeric characters
     * Used for tracking and customer reference
     */
    @NotBlank(message = "Tracking number is required")
    @Pattern(regexp = "^[A-Z0-9]{10,20}$", message = "Tracking number must have 10-20 alphanumeric characters")
    private String trackingNumber;

    /**
     * ID of the user who created this delivery
     * References the customer in the auth service
     * Must be a positive number
     */
    @NotNull(message = "User ID is required")
    @Positive(message = "User ID must be a positive number")
    private Long userId;

    /**
     * Type of delivery service selected
     * Allowed values: STANDARD, EXPRESS, OVERNIGHT, SAME_DAY
     * Affects delivery time and pricing
     */
    @NotBlank(message = "Service type is required")
    @Pattern(regexp = "^(STANDARD|EXPRESS|OVERNIGHT|SAME_DAY)$", message = "Service type must be STANDARD, EXPRESS, OVERNIGHT, or SAME_DAY")
    private String serviceType;

    /**
     * Current status of the delivery
     * Allowed values: CREATED, PICKED, IN_TRANSIT, DELIVERED, FAILED, CANCELLED
     * Status transitions are controlled by business logic
     */
    @NotBlank(message = "Status is required")
    @Pattern(regexp = "^(CREATED|PICKED|IN_TRANSIT|OUT_FOR_DELIVERY|DELIVERED|FAILED|CANCELLED)$", message = "Status must be CREATED, PICKED, IN_TRANSIT, OUT_FOR_DELIVERY, DELIVERED, FAILED, or CANCELLED")
    private String status;

    /**
     * Estimated date for delivery completion
     * Used to inform the customer when to expect their parcel
     */
    private java.time.LocalDate expectedDeliveryDate;

    /**
     * Timestamp when the delivery was created
     */
    private java.time.LocalDateTime createdAt;

    /**
     * Timestamp when the delivery was completed
     */
    private java.time.LocalDateTime deliveredAt;

    /**
     * Total amount charged for the delivery
     * Includes base rate, service type premium, and any additional charges
     * Stored as decimal with 2 decimal places precision
     */
    @Positive(message = "Total amount must be greater than 0")
    @Digits(integer = 10, fraction = 2, message = "Total amount must have at most 10 integer digits and 2 decimal places")
    private Double totalAmount;

    /**
     * Associated parcel information
     * One-to-One relationship: each delivery has exactly one parcel
     * Cascade ALL operations to maintain data consistency
     */
    @OneToOne(mappedBy = "delivery", cascade = CascadeType.ALL)
    private Parcel parcel;

    /**
     * List of addresses associated with this delivery
     * One-to-Many relationship: includes pickup and delivery addresses
     * Cascade ALL operations to maintain data consistency
     */
    @OneToMany(mappedBy = "delivery", cascade = CascadeType.ALL)
    private List<Address> addresses;

    /**
     * Default constructor required by JPA
     */
    public Delivery() {}

    /**
     * Parameterized constructor for creating delivery instances
     *
     * @param id unique identifier (can be null for new entities)
     * @param trackingNumber unique tracking number for the delivery
     * @param userId ID of the customer who owns this delivery
     * @param serviceType type of delivery service (STANDARD/EXPRESS/etc.)
     * @param status current delivery status
     * @param totalAmount total cost of the delivery
     */
    public Delivery(Long id, String trackingNumber, Long userId,
                    String serviceType, String status, Double totalAmount) {
        this.id = id;
        this.trackingNumber = trackingNumber;
        this.userId = userId;
        this.serviceType = serviceType;
        this.status = status;
        this.totalAmount = totalAmount;
    }

    // Getters & Setters

    /**
     * Get the delivery ID
     * @return the unique identifier of this delivery
     */
    public Long getId() { return id; }

    /**
     * Set the delivery ID
     * @param id the unique identifier to set
     */
    public void setId(Long id) { this.id = id; }

    /**
     * Get the tracking number
     * @return the unique tracking number for this delivery
     */
    public String getTrackingNumber() { return trackingNumber; }

    /**
     * Set the tracking number
     * @param trackingNumber the tracking number to set
     */
    public void setTrackingNumber(String trackingNumber) { this.trackingNumber = trackingNumber; }

    /**
     * Get the user ID
     * @return the ID of the customer who owns this delivery
     */
    public Long getUserId() { return userId; }

    /**
     * Set the user ID
     * @param userId the customer ID to set
     */
    public void setUserId(Long userId) { this.userId = userId; }

    /**
     * Get the service type
     * @return the type of delivery service (STANDARD/EXPRESS/etc.)
     */
    public String getServiceType() { return serviceType; }

    /**
     * Set the service type
     * @param serviceType the service type to set
     */
    public void setServiceType(String serviceType) { this.serviceType = serviceType; }

    /**
     * Get the delivery status
     * @return the current status of the delivery
     */
    public String getStatus() { return status; }

    /**
     * Set the delivery status
     * @param status the status to set
     */
    public void setStatus(String status) { this.status = status; }

    /**
     * Get the total amount
     * @return the total cost of the delivery
     */
    public Double getTotalAmount() { return totalAmount; }

    /**
     * Set the total amount
     * @param totalAmount the total cost to set
     */
    public void setTotalAmount(Double totalAmount) { this.totalAmount = totalAmount; }

    /**
     * Get the expected delivery date
     * @return the date when the delivery is expected
     */
    public java.time.LocalDate getExpectedDeliveryDate() { return expectedDeliveryDate; }

    /**
     * Set the expected delivery date
     * @param expectedDeliveryDate the date to set
     */
    public void setExpectedDeliveryDate(java.time.LocalDate expectedDeliveryDate) { this.expectedDeliveryDate = expectedDeliveryDate; }

    /**
     * Get the associated parcel
     * @return the parcel information for this delivery
     */
    public Parcel getParcel() { return parcel; }

    /**
     * Set the associated parcel
     * @param parcel the parcel to associate with this delivery
     */
    public void setParcel(Parcel parcel) { this.parcel = parcel; }

    /**
     * Get the list of addresses
     * @return the addresses associated with this delivery
     */
    public List<Address> getAddresses() { return addresses; }

    /**
     * Set the list of addresses
     * @param addresses the addresses to associate with this delivery
     */
    public void setAddresses(List<Address> addresses) { this.addresses = addresses; }
    public java.time.LocalDateTime getCreatedAt() { return createdAt; }
    public void setCreatedAt(java.time.LocalDateTime createdAt) { this.createdAt = createdAt; }

    public java.time.LocalDateTime getDeliveredAt() { return deliveredAt; }
    public void setDeliveredAt(java.time.LocalDateTime deliveredAt) { this.deliveredAt = deliveredAt; }
}