package com.capg.smartcourier.entity;

import jakarta.persistence.*;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Parcel Entity
 *
 * Represents the physical package being delivered in the Smart Courier System.
 */
@Entity
public class Parcel {

    /**
     * Unique identifier for the parcel
     * Auto-generated by the database using IDENTITY strategy
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Weight of the parcel in kilograms
     * Used for pricing calculations and handling requirements
     * Must be positive for valid parcels
     */
    private Double weight;

    /**
     * Physical dimensions of the parcel
     * Format: "Length x Width x Height" (e.g., "30x20x15 cm")
     * Used for packaging and space planning
     */
    private String dimensions;

    /**
     * Indicates if the parcel contains fragile items
     * Affects handling procedures and packaging requirements
     * True for items requiring extra care during transport
     */
    private Boolean fragile;

    /**
     * Associated delivery information
     * One-to-One relationship: each parcel belongs to one delivery
     * Foreign key relationship with delivery_id column
     * JsonIgnore prevents circular serialization in REST responses
     */
    @OneToOne
    @JoinColumn(name = "delivery_id")
    @JsonIgnore
    private Delivery delivery;

    /**
     * Default constructor required by JPA
     */
    public Parcel() {}

    // Getters & Setters

    /**
     * Get the parcel ID
     * @return the unique identifier of this parcel
     */
    public Long getId() { return id; }

    /**
     * Set the parcel ID
     * @param id the unique identifier to set
     */
    public void setId(Long id) { this.id = id; }

    /**
     * Get the parcel weight
     * @return the weight in kilograms
     */
    public Double getWeight() { return weight; }

    /**
     * Set the parcel weight
     * @param weight the weight in kilograms to set
     */
    public void setWeight(Double weight) { this.weight = weight; }

    /**
     * Get the parcel dimensions
     * @return the dimensions as a formatted string
     */
    public String getDimensions() { return dimensions; }

    /**
     * Set the parcel dimensions
     * @param dimensions the dimensions string to set (format: LxWxH)
     */
    public void setDimensions(String dimensions) { this.dimensions = dimensions; }

    /**
     * Check if the parcel is fragile
     * @return true if the parcel requires special handling
     */
    public Boolean getFragile() { return fragile; }

    /**
     * Set the fragile status
     * @param fragile true if the parcel needs special handling
     */
    public void setFragile(Boolean fragile) { this.fragile = fragile; }

    /**
     * Get the associated delivery
     * @return the delivery that this parcel belongs to
     */
    public Delivery getDelivery() { return delivery; }

    /**
     * Set the associated delivery
     * @param delivery the delivery to associate with this parcel
     */
    public void setDelivery(Delivery delivery) { this.delivery = delivery; }
}