package com.capg.smartcourier.entity;

import jakarta.persistence.*;

/**
 * Role Entity - Represents user roles in the Smart Courier System
 *
 * This entity defines the different roles that users can have in the system.
 * Roles are used for authorization and access control throughout the application.
 * The system supports role-based access control (RBAC) using these roles.
 *
 * Database Mapping:
 * - Table: role (automatically created by Hibernate)
 * - Primary Key: id (auto-generated)
 * - Relationships: Many-to-Many with User entity (bidirectional)
 *
 * Common Roles:
 * - USER: Standard user with basic access
 * - ADMIN: Administrative user with elevated privileges
 * - COURIER: Delivery personnel role
 * - CUSTOMER: Customer role for order placement
 *
 * Security Implementation:
 * - Roles are eagerly loaded with users for performance
 * - Used by Spring Security for method-level and URL-level authorization
 * - Supports hierarchical role definitions if needed
 *
 * @author Smart Courier Development Team
 * @version 1.0.0
 * @since 2026-03-30
 */
@Entity
public class Role {

    /**
     * Unique identifier for the role
     * Auto-generated by database using IDENTITY strategy
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The name of the role (e.g., "USER", "ADMIN", "COURIER")
     * This is the human-readable identifier used for authorization checks
     * Should follow naming conventions (uppercase, no spaces)
     */
    private String name;

    /**
     * Default constructor required by JPA
     * Initializes an empty Role object
     */
    public Role() {}

    /**
     * Parameterized constructor for creating Role instances
     *
     * @param id the unique identifier (can be null for new roles)
     * @param name the role name (e.g., "ADMIN", "USER")
     */
    public Role(Long id, String name) {
        this.id = id;
        this.name = name;
    }

    /**
     * Gets the role's unique identifier
     * @return the role ID
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the role's unique identifier
     * @param id the role ID to set
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Gets the role name
     * @return the role name
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the role name
     * @param name the role name to set
     */
    public void setName(String name) {
        this.name = name;
    }
}