package com.capg.smartcourier.entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.*;
import java.util.Set;

/**
 * User Entity - Represents a user in the Smart Courier System
 *
 * This entity stores user account information including authentication credentials,
 * personal details, and role assignments. It serves as the core user model for
 * the authentication and authorization system.
 *
 * Database Mapping:
 * - Table: user (automatically created by Hibernate)
 * - Primary Key: id (auto-generated)
 * - Relationships: Many-to-Many with Role entity
 *
 * Security Features:
 * - Password encryption using BCrypt (handled in service layer)
 * - Input validation with Jakarta Bean Validation
 * - Role-based access control through roles collection
 *
 * Validation Rules:
 * - Username: 3-50 chars, alphanumeric + underscore/hyphen only
 * - Email: Valid email format required
 * - Password: 8-100 chars with complexity requirements
 *   (uppercase, lowercase, digit, special character)
 *
 * @author Smart Courier Development Team
 * @version 1.0.0
 * @since 2026-03-30
 */
@Entity
public class User {

    /**
     * Unique identifier for the user
     * Auto-generated by database using IDENTITY strategy
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * User's unique username for login
     * Must be between 3-50 characters and contain only valid characters
     * Used as the primary login identifier
     */
    @NotBlank(message = "Username is required")
    @Size(min = 3, max = 50, message = "Username must be between 3 and 50 characters")
    @Pattern(regexp = "^[a-zA-Z0-9_-]+$", message = "Username can only contain letters, numbers, underscore and hyphen")
    private String username;

    /**
     * User's email address
     * Must be a valid email format
     * Used for account verification and password recovery
     */
    @NotBlank(message = "Email is required")
    @Email(message = "Email should be valid")
    private String email;

    /**
     * User's password (stored encrypted)
     * Must meet complexity requirements for security
     * Encrypted using BCrypt before storage
     */
    @NotBlank(message = "Password is required")
    @Size(min = 8, max = 100, message = "Password must be between 8 and 100 characters")
    private String password;

    /**
     * User's assigned roles for authorization
     * Many-to-Many relationship with Role entity
     * EAGER fetching to ensure roles are always loaded with user
     * Supports role-based access control (RBAC)
     */
    @ManyToMany(fetch = FetchType.EAGER, cascade = {CascadeType.MERGE})
    private Set<Role> roles;

    /**
     * Default constructor required by JPA
     * Initializes an empty User object
     */
    public User() {}

    /**
     * Parameterized constructor for creating User instances
     *
     * @param id the unique identifier (can be null for new users)
     * @param username the user's login username
     * @param email the user's email address
     * @param password the user's password (will be encrypted)
     * @param roles the set of roles assigned to the user
     */
    public User(Long id, String username, String email, String password, Set<Role> roles) {
        this.id = id;
        this.username = username;
        this.email = email;
        this.password = password;
        this.roles = roles;
    }

    /**
     * Gets the user's unique identifier
     * @return the user ID
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the user's unique identifier
     * @param id the user ID to set
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Gets the user's username
     * @return the username
     */
    public String getUsername() {
        return username;
    }

    /**
     * Sets the user's username
     * @param username the username to set
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * Gets the user's email address
     * @return the email address
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the user's email address
     * @param email the email address to set
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Gets the user's password
     * Note: This returns the encrypted password, not plain text
     * @return the encrypted password
     */
    public String getPassword() {
        return password;
    }

    /**
     * Sets the user's password
     * Note: Password should be encrypted before calling this method
     * @param password the encrypted password to set
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * Gets the set of roles assigned to the user
     * @return the set of roles
     */
    public Set<Role> getRoles() {
        return roles;
    }

    /**
     * Sets the roles assigned to the user
     * @param roles the set of roles to assign
     */
    public void setRoles(Set<Role> roles) {
        this.roles = roles;
    }
}