package com.capg.smartcourier.entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.*;
import java.time.LocalDateTime;

/**
 * Delivery Proof Entity
 *
 * Represents proof of delivery in the Smart Courier System.
 */
@Entity
public class DeliveryProof {

    /**
     * Unique identifier for the delivery proof
     * Auto-generated by the database using IDENTITY strategy
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * ID of the delivery this proof belongs to
     * References the delivery in the delivery service
     * Must be a valid, existing delivery ID
     */
    @NotNull(message = "Delivery ID is required")
    @Positive(message = "Delivery ID must be a positive number")
    private Long deliveryId;

    /**
     * Type of proof being provided
     * Allowed values: PHOTO, SIGNATURE, VIDEO, DOCUMENT, OTHER
     * Determines how the proof data should be processed and displayed
     */
    @NotBlank(message = "Proof type is required")
    @Pattern(regexp = "^(PHOTO|SIGNATURE|VIDEO|DOCUMENT|OTHER)$", message = "Proof type must be PHOTO, SIGNATURE, VIDEO, DOCUMENT, or OTHER")
    private String proofType; // PHOTO, SIGNATURE, etc.

    /**
     * The actual proof data content
     * Can be Base64 encoded content or file system path
     * Format depends on proof type (image, signature, document, etc.)
     * Minimum length ensures meaningful content
     */
    @NotBlank(message = "Proof data is required")
    @Size(min = 10, message = "Proof data must not be empty")
    private String proofData; // Base64 encoded or file path

    /**
     * Timestamp when the proof was captured
     * Automatically set to current time during creation
     * Used for audit trail and delivery verification
     */
    private LocalDateTime capturedAt;

    /**
     * Location where the proof was captured
     * GPS coordinates or descriptive location string
     * Must match delivery destination for validity
     */
    @NotBlank(message = "Location is required")
    @Size(min = 3, max = 200, message = "Location must be between 3 and 200 characters")
    private String location;

    /**
     * ID of the user who captured this proof
     * References the delivery personnel in the auth service
     * Must be a valid user with delivery permissions
     */
    @NotNull(message = "Captured by (User ID) is required")
    @Positive(message = "User ID must be a positive number")
    private Long capturedBy; // User ID who captured the proof

    /**
     * Default constructor required by JPA
     */
    public DeliveryProof() {}

    /**
     * Parameterized constructor for creating delivery proof instances
     *
     * @param deliveryId ID of the delivery this proof belongs to
     * @param proofType type of proof (PHOTO, SIGNATURE, etc.)
     * @param proofData the actual proof content/data
     * @param location where the proof was captured
     * @param capturedBy ID of the user who captured the proof
     */
    public DeliveryProof(Long deliveryId, String proofType, String proofData, String location, Long capturedBy) {
        this.deliveryId = deliveryId;
        this.proofType = proofType;
        this.proofData = proofData;
        this.location = location;
        this.capturedBy = capturedBy;
        this.capturedAt = LocalDateTime.now();
    }

    // Getters and Setters

    /**
     * Get the proof ID
     * @return the unique identifier of this delivery proof
     */
    public Long getId() { return id; }

    /**
     * Set the proof ID
     * @param id the unique identifier to set
     */
    public void setId(Long id) { this.id = id; }

    /**
     * Get the delivery ID
     * @return the ID of the delivery this proof belongs to
     */
    public Long getDeliveryId() { return deliveryId; }

    /**
     * Set the delivery ID
     * @param deliveryId the delivery ID to set
     */
    public void setDeliveryId(Long deliveryId) { this.deliveryId = deliveryId; }

    /**
     * Get the proof type
     * @return the type of proof (PHOTO, SIGNATURE, etc.)
     */
    public String getProofType() { return proofType; }

    /**
     * Set the proof type
     * @param proofType the proof type to set
     */
    public void setProofType(String proofType) { this.proofType = proofType; }

    /**
     * Get the proof data
     * @return the proof content (Base64 or file path)
     */
    public String getProofData() { return proofData; }

    /**
     * Set the proof data
     * @param proofData the proof content to set
     */
    public void setProofData(String proofData) { this.proofData = proofData; }

    /**
     * Get the capture timestamp
     * @return when the proof was captured
     */
    public LocalDateTime getCapturedAt() { return capturedAt; }

    /**
     * Set the capture timestamp
     * @param capturedAt the timestamp to set
     */
    public void setCapturedAt(LocalDateTime capturedAt) { this.capturedAt = capturedAt; }

    /**
     * Get the capture location
     * @return where the proof was captured
     */
    public String getLocation() { return location; }

    /**
     * Set the capture location
     * @param location the location to set
     */
    public void setLocation(String location) { this.location = location; }

    /**
     * Get the user who captured the proof
     * @return the ID of the user who captured this proof
     */
    public Long getCapturedBy() { return capturedBy; }

    /**
     * Set the user who captured the proof
     * @param capturedBy the user ID to set
     */
    public void setCapturedBy(Long capturedBy) { this.capturedBy = capturedBy; }
}