package com.capg.smartcourier.entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.*;
import java.time.LocalDateTime;

/**
 * Document Entity
 *
 * Represents uploaded documents in the Smart Courier System.
 */
@Entity
public class Document {

    /**
     * Unique identifier for the document
     * Auto-generated by the database using IDENTITY strategy
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Original name of the uploaded file
     * Preserves user-provided filename for reference
     * Must not exceed maximum filename length
     */
    @NotBlank(message = "File name is required")
    @Size(max = 255, message = "File name must not exceed 255 characters")
    private String fileName;

    /**
     * MIME type of the file (e.g., application/pdf, image/jpeg)
     * Used for file validation and client handling
     * Must match allowed file types for security
     */
    @NotBlank(message = "File type is required")
    @Pattern(regexp = "^[a-zA-Z0-9/\\-+]{3,50}$", message = "File type must be valid (e.g., application/pdf)")
    private String fileType;

    /**
     * Size of the file in bytes
     * Used for storage quota management and validation
     * Must be positive and within allowed limits
     */
    @NotNull(message = "File size is required")
    @Positive(message = "File size must be greater than 0")
    @Max(value = 104857600, message = "File size must not exceed 100 MB")
    private Long fileSize;

    /**
     * Path where the file is stored
     * Can be local file system path or cloud storage URL
     * Used for file retrieval and management
     */
    @NotBlank(message = "File path is required")
    @Size(min = 3, max = 500, message = "File path must be between 3 and 500 characters")
    private String filePath;

    /**
     * ID of the delivery this document belongs to
     * Links document to specific delivery for access control
     * Must reference existing delivery
     */
    @NotNull(message = "Delivery ID is required")
    @Positive(message = "Delivery ID must be a positive number")
    private Long deliveryId;

    /**
     * ID of the user who uploaded the document
     * Ensures proper access control and audit trail
     * Must be authenticated user with appropriate permissions
     */
    @NotNull(message = "User ID is required")
    @Positive(message = "User ID must be a positive number")
    private Long userId;

    /**
     * Timestamp when the document was uploaded
     * Automatically set during document creation
     * Used for audit trail and file management
     */
    private LocalDateTime uploadedAt;

    /**
     * Default constructor required by JPA
     */
    public Document() {}

    /**
     * Parameterized constructor for creating document instances
     *
     * @param fileName original name of the uploaded file
     * @param fileType MIME type of the file
     * @param fileSize size of the file in bytes
     * @param filePath storage path of the file
     * @param deliveryId ID of associated delivery
     * @param userId ID of user who uploaded the file
     */
    public Document(String fileName, String fileType, Long fileSize, String filePath, Long deliveryId, Long userId) {
        this.fileName = fileName;
        this.fileType = fileType;
        this.fileSize = fileSize;
        this.filePath = filePath;
        this.deliveryId = deliveryId;
        this.userId = userId;
        this.uploadedAt = LocalDateTime.now();
    }

    // Getters and Setters

    /**
     * Get the document ID
     * @return the unique identifier of this document
     */
    public Long getId() { return id; }

    /**
     * Set the document ID
     * @param id the unique identifier to set
     */
    public void setId(Long id) { this.id = id; }

    /**
     * Get the file name
     * @return the original name of the uploaded file
     */
    public String getFileName() { return fileName; }

    /**
     * Set the file name
     * @param fileName the file name to set
     */
    public void setFileName(String fileName) { this.fileName = fileName; }

    /**
     * Get the file type
     * @return the MIME type of the file
     */
    public String getFileType() { return fileType; }

    /**
     * Set the file type
     * @param fileType the MIME type to set
     */
    public void setFileType(String fileType) { this.fileType = fileType; }

    /**
     * Get the file size
     * @return the size of the file in bytes
     */
    public Long getFileSize() { return fileSize; }

    /**
     * Set the file size
     * @param fileSize the file size in bytes to set
     */
    public void setFileSize(Long fileSize) { this.fileSize = fileSize; }

    /**
     * Get the file path
     * @return the storage path of the file
     */
    public String getFilePath() { return filePath; }

    /**
     * Set the file path
     * @param filePath the storage path to set
     */
    public void setFilePath(String filePath) { this.filePath = filePath; }

    /**
     * Get the delivery ID
     * @return the ID of the associated delivery
     */
    public Long getDeliveryId() { return deliveryId; }

    /**
     * Set the delivery ID
     * @param deliveryId the delivery ID to set
     */
    public void setDeliveryId(Long deliveryId) { this.deliveryId = deliveryId; }

    /**
     * Get the user ID
     * @return the ID of the user who uploaded the document
     */
    public Long getUserId() { return userId; }

    /**
     * Set the user ID
     * @param userId the user ID to set
     */
    public void setUserId(Long userId) { this.userId = userId; }

    /**
     * Get the upload timestamp
     * @return when the document was uploaded
     */
    public LocalDateTime getUploadedAt() { return uploadedAt; }

    /**
     * Set the upload timestamp
     * @param uploadedAt the timestamp to set
     */
    public void setUploadedAt(LocalDateTime uploadedAt) { this.uploadedAt = uploadedAt; }
}