package com.capg.smartcourier.entity;

import jakarta.persistence.*;

/**
 * Tracking Entity
 *
 * Represents a tracking record in the Smart Courier System's tracking service.
 */
@Entity
public class Tracking {

    /**
     * Unique identifier for the tracking record
     * Auto-generated by the database using IDENTITY strategy
     * Used for internal record management and updates
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Tracking number that uniquely identifies the delivery
     * Corresponds to the tracking number in the delivery service
     * Used to correlate tracking records with specific deliveries
     * Must match the format used in delivery service
     */
    private String trackingNumber;

    /**
     * Current status of the delivery
     * Enum values: CREATED, PICKED, IN_TRANSIT, DELIVERED, FAILED, CANCELLED
     * Represents the current state in the delivery workflow
     * Used for status displays and business logic decisions
     */
    private String status; // IN_TRANSIT, DELIVERED, etc.

    /**
     * Current location of the package
     * Describes where the package is physically located
     * Examples: "Distribution Center A", "In transit to New York", "Local Post Office"
     * Used for location tracking and customer updates
     */
    private String location;

    /**
     * Human-readable message describing the status update
     * Provides context and details about the current status
     * Examples: "Package picked up", "Out for delivery", "Delivered to recipient"
     * Displayed to customers in tracking interfaces
     */
    private String message;

    private java.time.LocalDateTime timestamp;

    private String description;

    /**
     * Default constructor required by JPA
     */
    public Tracking() {}

    // Getters & Setters

    /**
     * Get the tracking record ID
     * @return the unique identifier of this tracking record
     */
    public Long getId() { return id; }

    /**
     * Set the tracking record ID
     * @param id the unique identifier to set
     */
    public void setId(Long id) { this.id = id; }

    /**
     * Get the tracking number
     * @return the tracking number that identifies the delivery
     */
    public String getTrackingNumber() { return trackingNumber; }

    /**
     * Set the tracking number
     * @param trackingNumber the tracking number to set
     */
    public void setTrackingNumber(String trackingNumber) { this.trackingNumber = trackingNumber; }

    /**
     * Get the delivery status
     * @return the current status of the delivery
     */
    public String getStatus() { return status; }

    /**
     * Set the delivery status
     * @param status the status to set
     */
    public void setStatus(String status) { this.status = status; }

    /**
     * Get the current location
     * @return the location description of the package
     */
    public String getLocation() { return location; }

    /**
     * Set the current location
     * @param location the location to set
     */
    public void setLocation(String location) { this.location = location; }

    /**
     * Get the status message
     * @return the human-readable message describing the status
     */
    public String getMessage() { return message; }

    /**
     * Set the status message
     * @param message the message to set
     */
    public void setMessage(String message) { this.message = message; }

    public java.time.LocalDateTime getTimestamp() { return timestamp; }
    public void setTimestamp(java.time.LocalDateTime timestamp) { this.timestamp = timestamp; }

    public String getDescription() { return description; }
    public void setDescription(String description) { this.description = description; }
}